---
- name: Install SpaceVim
  shell: curl -sLf https://spacevim.org/install.sh | bash

- name: Add custom vim plugins
  blockinfile:
    path: $HOME/.SpaceVim.d/init.toml
    insertafter: EOF
    content: "{{ custom_vim_plugins }}"

- name: Add autoformat terraform on save to vimrc 
  lineinfile:
    path: $HOME/.SpaceVim/vimrc
    insertafter: EOF
    line: 'let g:terraform_fmt_on_save=1'
