---
- name: Configure Kali
  hosts: all
  vars:
    logrotate_scripts:
      - name: ansible
        path: "/var/log/ansible.log"
        options:
          - daily
          - missingok
          - rotate 7
          - maxage 7
          - dateext
          - dateyesterday

  roles:
    - nickhammond.logrotate
    - cmprescott.chrome
    - packages
    - docker
    - space_vim
    - oh_my_zsh
    - dot_files
    - common
    - seclists
