---
- name: Add docker gpg key
  apt_key:
    url: https://download.docker.com/linux/debian/gpg
    state: present
  become: true

  #- name: Configure docker apt repo
  #shell: echo 'deb https://download.docker.com/linux/debian stretch stable' > /etc/apt/sources.list.d/docker.list
  #become: true

- name: Configure docker apt repo
  apt_repository: 
    repo: 'deb https://download.docker.com/linux/debian stretch stable' 
    state: present 
    filename: 'docker' 
    update_cache: 'yes'
  become: true

- name: Upgrade all packages
  apt:
    upgrade: full
    update_cache: yes
    cache_valid_time: 3600
  become: true

- name: Remove useless packages from the cache
  apt:
    autoclean: yes
  become: true

- name: Remove dependencies that are no longer required
  apt:
    autoremove: yes
  become: true

- name: Install apt packages
  apt:
    name: "{{ packages }}"
    state: present
  become: true
