---
- name: Clone SecLists repo
  git:
    repo: https://github.com/danielmiessler/SecLists/
    dest: "{{ ansible_env.HOME }}/SecLists"

- name: Keep SecLists updated
  cron:
    name: 'Update SecLists every Sunday at 07:00PM'
    minute: 0
    hour: 19
    weekday: 0
    job: "cd {{ ansible_env.HOME }}/SecLists && git pull origin master"
