---
- name: Get X2Go APT GPG key
  apt_key:
    id: E1F958385BFE2B6E
    keyserver: '{{ ansible_local.core.keyserver
                   if (ansible_local|d() and ansible_local.core|d() and
                       ansible_local.core.keyserver|d())
                   else "hkp://pool.sks-keyservers.net" }}'

- name: Configure X2Go APT repository
  apt_repository:
    repo: 'deb http://packages.x2go.org/debian stretch main'
    update_cache: True

- name: Install x2goserver
  apt:
    name: "x2goserver"
    state: present
  become: true
